apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: casperdata-cert-testnet
spec:
  secretName: casperdata-cert-testnet
  issuerRef:
    name: letsencrypt-prod
  commonName: data.testnet.casperholders.com
  dnsNames:
    - data.testnet.casperholders.com
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: casperbackup-cert-testnet
spec:
  secretName: casperbackup-cert-testnet
  issuerRef:
    name: letsencrypt-prod
  commonName: backup.testnet.casperholders.io
  dnsNames:
    - backup.testnet.casperholders.io
