apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: casperdata-cert
spec:
  secretName: casperdata-cert
  issuerRef:
    name: letsencrypt-prod
  commonName: data.testnet.casperholders.com
  dnsNames:
    - data.testnet.casperholders.com
