apiVersion: v1
kind: ConfigMap
metadata:
  name: casperdata-config-testnet
data:
  DATABASE_URL: "postgres://postgres@casperdata-db-service-testnet:5432/casperdata-testnet"
  LIMIT_BULK_INSERT: "1000"
  BASE_RANDOM_THROTTLE_NUMBER: "10"
  RPC_URL: "http://176.9.125.5:8500/rpc"
  LOOP: "60"
  NODE_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config-testnet
data:
  PGRST_DB_URI: "postgres://postgres@casperdata-db-service-testnet:5432/casperdata-testnet"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "postgres"
  OPENAPI_MODE: "ignore-privileges"
  OPENAPI_SERVER_PROX_URI: "https://data.testnet.casperholders.com/swagger"
  MAX_ROWS: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-testnet
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        autoindex on;
      }
    }
