apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casperdata-cert
spec:
  secretName: casperdata-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: data.casperholders.com
  dnsNames:
    - data.casperholders.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casperbackup-cert
spec:
  secretName: casperbackup-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: backup.casperholders.io
  dnsNames:
    - backup.casperholders.io
